---
- name: load docker info as facts
  docker_info_facts:

- name: create swarm_manager_operational group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_operational, swarm_operational
  with_items: "{{ groups['manager'] }}"
  when: "hostvars[item]['docker_info']['Swarm']['LocalNodeState'] == 'active'"
  run_once: true

- name: create swarm_manager_bootstrap group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_bootstrap, swarm_bootstrap
  with_items: "{{ groups['manager'] }}"
  when: "hostvars[item]['docker_info']['Swarm']['LocalNodeState'] == 'inactive'"
  run_once: true

- name: create swarm_worker_operational group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_worker_operational, swarm_operational
  with_items: "{{ groups['worker'] }}"
  when: "hostvars[item]['docker_info']['Swarm']['LocalNodeState'] == 'active'"
  run_once: true

- name: create swarm_worker_bootstrap group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_worker_bootstrap, swarm_bootstrap
  with_items: "{{ groups['worker'] }}"
  when: "hostvars[item]['docker_info']['Swarm']['LocalNodeState'] == 'inactive'"
  run_once: true
