- hosts: all
  gather_facts: false
  roles:
    - role: bootstrap-coreos
      tags:
        - bootstrap
        - coreos
    - role: bootstrap-docker
      tags:
        - bootstrap
        - docker
    - role: bootstrap-rexray
      tags:
        - bootstrap
        - rexray

- hosts: manager
  roles:
    - role: docker-registry
      tags:
        - docker
        - docker_registry

- hosts: worker
  roles:
    - role: docker-registry-mirror
      tags:
        - docker
        - docker_registry
        - docker_registry_mirror
