- hosts: manager, worker
  gather_facts: false
  roles:
    - role: docker-swarm-grouping
      tags:
        - docker
        - swarm
    - role: docker-swarm-leave
      when: >
        (groups['swarm_operational'] is defined)
        and
        (inventory_hostname in groups['swarm_operational'])
      tags:
        - docker
        - swarm
