---
- name: "[shell] retrieve swarm manager token"
  shell: docker swarm join-token -q manager
  register: swarm_manager_token
  run_once: true

- name: "[shell] retrieve swarm worker token"
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
  run_once: true
