---
- name: Ensure that /etc/nginx/conf.d
  become: true
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: Build /etc/nginx/conf.d/docker-registry-mirror.conf from template
  become: true
  template:
    src: docker-registry-mirror.j2.nginx
    dest: /etc/nginx/conf.d/docker-registry-mirror.conf
    mode: 0640
  register: docker_registry_nginx_conf

- name: Copy /etc/systemd/system/docker-registry-mirror.service
  become: true
  copy:
    src: docker-registry-mirror.service
    dest: /etc/systemd/system/docker-registry-mirror.service
    mode: 0640
  register: docker_registry_mirror_service

- name: Restart if service changed
  become: true
  systemd:
    name: docker-registry-mirror
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: (docker_registry_nginx_conf | changed) or (docker_registry_mirror_service | changed)

- name: Ensure that started
  become: true
  systemd:
    name: docker-registry-mirror
    state: started
