---
- name: "[file] Ensure that /etc/nginx/conf.d"
  become: true
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: "[template] Build /etc/nginx/conf.d/docker-registry-mirror.conf"
  become: true
  template:
    src: docker-registry-mirror.j2.nginx
    dest: /etc/nginx/conf.d/docker-registry-mirror.conf
    mode: 0640
  register: docker_registry_nginx_conf

- name: "[template] Build /etc/systemd/system/docker-registry-mirror.service"
  become: true
  template:
    src: docker-registry-mirror.j2.service
    dest: /etc/systemd/system/docker-registry-mirror.service
    mode: 0640
  register: docker_registry_mirror_service

- name: "[systemd] Restart if service changed"
  become: true
  systemd:
    name: docker-registry-mirror
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: (docker_registry_nginx_conf | changed) or (docker_registry_mirror_service | changed)

- name: "[systemd] Ensure that started"
  become: true
  systemd:
    name: docker-registry-mirror
    state: started
