---
- name: Add manager hosts as insecure registries and registry mirrors
  become: true
  lineinfile:
    dest: /etc/default/docker
    regexp: '^DOCKER_OPTS="(.*)\s?(--insecure-registry=.*)?"$'
    line: DOCKER_OPTS="\1{% for host in groups['manager'] %} --insecure-registry={{ hostvars[host]['ansible_' + iface]['ipv4']['address'] }}:5000 --registry-mirror=http://{{ hostvars[host]['ansible_' + iface]['ipv4']['address'] }}:5000{% endfor %}"
    backrefs: yes
  notify: Reload
