---
- block:
  - name: Purge DOCKER_OPTS
    become: true
    lineinfile:
      dest: /etc/default/docker
      regexp: '^DOCKER_OPTS=".*"$'
      line: DOCKER_OPTS=""
    notify: Reload
    register: docker_opts_purge
    when: docker.options.purge is defined and docker.options.purge == True
    tags:
      - docker

  - name: Ensure that Docker started
    become: true
    systemd:
      name: docker
      state: started
    tags:
      - docker

  - block:
    - name: Check experimental status
      shell: >
        {% raw -%}
          docker version -f '{{.Server.Experimental}}'
        {% endraw -%}
      changed_when: false
      register: docker_experimental
      tags:
        - docker

    - name: Enable --experimental
      become: true
      lineinfile:
        dest: /etc/default/docker
        regexp: '^DOCKER_OPTS="(.*)"$'
        line: DOCKER_OPTS="\1 --experimental"
        backrefs: yes
      notify: Reload
      when: docker.options.experimental == True and (docker_experimental.stdout != 'true' or (docker_opts_purge is defined and docker_opts_purge.changed == True))
      tags:
        - docker

    - name: Disable --experimental
      become: true
      lineinfile:
        dest: /etc/default/docker
        regexp: ^DOCKER_OPTS="(.*)(--experimental)(.*)"$
        line: 'DOCKER_OPTS="\1\3"'
        backrefs: yes
      notify: Reload
      when: docker.options.experimental == False and (docker_experimental.stdout != 'false' or (docker_opts_purge is defined and docker_opts_purge.changed == True))
      tags:
        - docker
    when: docker.options.experimental is defined
  - name: Strip leading spaces
    become: true
    lineinfile:
      dest: /etc/default/docker
      regexp: '^DOCKER_OPTS="(\s*)(.*)"$'
      line: 'DOCKER_OPTS="\2"'
      backrefs: yes
    tags:
      - docker
  when: docker.options is defined
