---
- block:
  - name: Check /var/bash-completion/bash_completion
    become: true
    stat:
      path: /var/bash-completion/bash_completion
    register: bash_completion

  - name: Install bash completion
    become: true
    shell: >
      toolbox dnf -y install bash-completion wget \
      && toolbox cp /usr/share/bash-completion /media/root/var/ -R  \
      && source /var/bash-completion/bash_completion \
      && cp $(readlink .bashrc) .bashrc.new && mv .bashrc.new .bashrc \
      && echo "source /var/bash-completion/bash_completion" >> ~/.bashrc
    when:
      - bash_completion.stat.exists == False

  - block:
    - name: Check Docker
      become: true
      stat:
        path: /var/bash-completion/completions/docker
      register: docker_completion
    - name: Docker
      become: true
      shell: >
        toolbox wget https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker -O /media/root/var/bash-completion/completions/docker
      when: docker_completion.stat.exists == False
    when: completions.docker == True
  when: completions.install == True
