---
- name: "[copy] Change toolbox default image to Ubuntu"
  copy:
    src: .toolboxrc
    dest: $HOME/.toolboxrc
    mode: 0644

- block:
  - name: "[stat] Check is bash-completion installed"
    become: true
    stat:
      path: /var/bash-completion/bash_completion
    register: bash_completion

  - name: "[shell] Install bash-completion"
    shell: >
      toolbox apt-get update \
      && toolbox apt-get -y install bash-completion \
      && toolbox cp /usr/share/bash-completion /media/root/var/ -R
    when:
      - bash_completion.stat.exists == False

  - block:
    - name: "[stat] Check is Docker completion installed"
      become: true
      stat:
        path: /var/bash-completion/completions/docker
      register: docker_completion

    - name: "[shell] Install Docker completion"
      become: true
      shell: >
        wget https://raw.githubusercontent.com/docker/docker-ce/master/components/engine/contrib/completion/bash/docker -O /var/bash-completion/completions/docker
      args:
        warn: false
      when: >
        docker_completion.stat.exists == False
        or docker_completion.stat.size == 0
        or completions.docker == 'upgrade'
    when: completions.docker is defined and (completions.docker in ['install', 'upgrade'])

  - name: "[stat] Stat $HOME/.bashrc"
    stat:
      path: $HOME/.bashrc
    register: bashrc

  - name: "[shell] Unlink .bashrc"
    shell: >
      cp $(readlink .bashrc) .bashrc.new && mv .bashrc.new .bashrc
    when: bashrc.stat.islnk is defined and bashrc.stat.islnk

  - name: "[lineinfile] Source /var/bash-completion/bash_completion"
    lineinfile:
      path: $HOME/.bashrc
      line: 'source /var/bash-completion/bash_completion'
  when: completions is defined
