---
- name: initialize swarm cluster
  vars:
    iface: "{{ swarm.iface | default('eth0') }}"
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_' + iface]['ipv4']['address'] }}"
  shell: >
    docker swarm init
    --advertise-addr={{ advertise_addr }}:2377
  register: init_first_node
  run_once: true

- name: add initialized host to swarm_manager_operational group
  add_host:
    hostname: "{{ inventory_hostname }}"
    groups: swarm_manager_operational, swarm_operational
  when: init_first_node | changed
  run_once: true
