---
- name: Build /etc/systemd/system/docker-registry.service from template
  become: true
  template:
    src: docker-registry.j2.service
    dest: /etc/systemd/system/docker-registry.service
    mode: 0640
  register: docker_registry_service
  tags:
    - docker
    - docker-registry

- name: Restart if service changed
  become: true
  systemd:
    name: docker-registry
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: docker_registry_service | changed
  tags:
    - docker
    - docker-registry

- name: Ensure that started
  become: true
  systemd:
    name: docker-registry
    state: started
  tags:
    - docker
    - docker-registry
