---
- name: Build /etc/systemd/system/docker-registry.service from template
  vars:
    volume_name: "{{ inventory_hostname | regex_replace('_', '-') }}-registry-data"
  become: true
  template:
    src: docker-registry.j2.service
    dest: /etc/systemd/system/docker-registry.service
    mode: 0640
  register: docker_registry_service

- name: Enable
  become: true
  systemd:
    name: docker-registry
    enabled: yes
    state: started
  register: docker_registry_service_enable

- name: Restart if service changed
  become: true
  systemd:
    name: docker-registry
    daemon_reload: yes
    state: restarted
  when: (docker_registry_service | changed) and docker_registry_service_enable.changed == False

- name: Ensure that started
  become: true
  systemd:
    name: docker-registry
    state: started
